function createfigure(YMatrix1)
%CREATEFIGURE(YMATRIX1)
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 01-Jul-2013 17:35:56

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'XGrid','on');
hold(axes1,'all');

% Create multiple lines using matrix input to plot
plot1 = plot(YMatrix1,'Parent',axes1,'LineWidth',2);
set(plot1(1),'Color',[0 0.5 0],'DisplayName','MAE RNA');
set(plot1(2),'LineStyle','--','Color',[0 0.5 0],'DisplayName','MAE RNE');
set(plot1(3),'LineStyle','--','Color',[1 0 0],'DisplayName','PRODUCTO RMSE y MAE RNE');
set(plot1(4),'Color',[1 0 0],'DisplayName','PRODUCTO RMSE y MAE RNA');
set(plot1(5),'LineStyle','--','DisplayName','RMSE RNE');
set(plot1(6),'DisplayName','RMSE RNA');


% Create xlabel
xlabel('Etapa de Desempeño');

% Create ylabel
ylabel('Valor Medida de Evaluación');

% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.686188384577844 0.437089201877935 0.180819912152269 0.328638497652582]);

